import express from "express";
import authRoute from "./auth.route.js";
import categoryRoute from "./category.route.js";
import subCategoryRoute from "./subCategory.route.js";
import subSubCategoryRoute from "./subSubCategory.route.js";
import colorRoute from "./color.routes.js";
import sizeRoute from "./size.route.js";
import brandRoute from "./brand.route.js";
import productRoute from "./product.route.js";
import blogRoute from "./blog.route.js";
import blogCategoryRoute from "./blogCategory.route.js";
import carouselRoute from "./carousel.route.js";
import clientRoute from "./client.route.js";
import promotionRoute from "./promotion.route.js";
import testimonialRoute from "./testimonial.route.js";
import youTubeVideoRoute from "./youTubeVideo.route.js";
import orderRoute from "./order.route.js";
import dashboardRoute from "./dashboard.route.js";
import billingShippingPolicyRoute from "./billingShippingPolicy.route.js";
import cookiePolicyRoute from "./cookiePolicy.route.js";
import disclaimerRoute from "./disclaimer.route.js";
import privacyPolicyRoute from "./privacyPolicy.route.js";
import returnRefundPolicyRoute from "./returnRefundPolicy.route.js";
import termConditionRoute from "./termCondition.route.js";

const router = express.Router();

router.use("/auth", authRoute);
router.use("/category", categoryRoute);
router.use("/sub-category", subCategoryRoute);
router.use("/sub-sub-category", subSubCategoryRoute);
router.use("/color", colorRoute);
router.use("/size", sizeRoute);
router.use("/brand", brandRoute);
router.use("/product", productRoute);
router.use("/blog", blogRoute);
router.use("/blog-category", blogCategoryRoute);
router.use("/carousel", carouselRoute);
router.use("/client", clientRoute);
router.use("/promotion", promotionRoute);
router.use("/testimonial", testimonialRoute);
router.use("/youtube-video", youTubeVideoRoute);
router.use("/order", orderRoute);
router.use("/dashboard", dashboardRoute);
router.use("/billing-shipping-policy", billingShippingPolicyRoute);
router.use("/cookie-policy", cookiePolicyRoute);
router.use("/disclaimer", disclaimerRoute);
router.use("/privacy-policy", privacyPolicyRoute);
router.use("/return-refund-policy", returnRefundPolicyRoute);
router.use("/term-condition", termConditionRoute);

export default router;